set_tower_organization_name: ""
set_tower_inventory_name: ""
set_inventory_ansible_user: ""
set_tower_host_name: ""
set_tower_host_url: ""
set_tower_project_name: ""
set_tower_project_git_url: "https://github.com/daljitdokal/ansible-mysql-backup.git"
set_tower_job_template_name: "Database daily backup"
set_tower_job_template_playbook_name: "database_backup_playbook_awx.yaml"
set_remote_db_backup_folder_path: ""
set_local_db_backup_folder_path: ""
set_remote_db_file_name_pattern_to_delete: ""